name: 'Build'

on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    -name: Setup static web files
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: gulp default

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.0
        target: esp32s3
        path: ''